baseURL: https://standy.me/
languageCode: en-us
title: Andrew's website
theme: PaperMod
googleAnalytics: G-C5RG2DYTWS
params:
  profileMode:
    enabled: true
    title: Andrew Stepanov
    subtitle: AI expert turned VC
    imageUrl: "photo_2023-03-18 15.53.44.jpeg" # optional
    imageWidth: 180 # custom size
    imageHeight: 180 # custom size
  socialIcons:
    - name: email
      url: mailto:hi@standy.me
    - name: linkedin
      url: https://linkedin.com/in/standy66
    - name: telegram
      url: https://t.me/standy
    - name: github
      url: https://github.com/standy66
    - name: instagram
      url: https://instagram.com/astepanov95
    - name: stackoverflow
      url: https://stackoverflow.com/users/1939748/standy
